import Head from "next/head";
import { useState } from "react";

interface Point {
    x: number,
    y: number
};

export default function Home() {
    const [ points, setPoints ] = useState<Point[]>([]);
    const [ answer, setAnswer ] = useState<number | null>(null);
    return (
        <>
            <Head>
                <title>Area Calculator</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-zinc-900 min-h-screen p-10 text-white">
                <div className="flex flex-col gap-3 justify-center">
                    <h1 className="font-bold text-5xl py-2">Area Calculator</h1>
                    <p className="py-3">Enter the vertices of the polygon, and it will calculate the area. When entering the vertices, make sure you enter the vertices in either clockwise or counter-clockwise order! Enter the vertices in (x, y) format, with first column being x value and second column being y value.</p>
                    <div className="flex flex-col gap-3">
                        <div className="flex flex-col gap-2 w-1/8">
                            {points.map((point, idx) => (
                                <div className="flex flex-row gap-3" key={idx}>
                                    <input id={`x-${idx}`} className="bg-zinc-700 rounded py-2 px-2"/>
                                    <input id={`y-${idx}`} className="bg-zinc-700 rounded py-2 px-2"/>
                                </div>
                            ))}
                        </div>
                        <div className="flex flex-row gap-5">
                            <button onClick={() => {
                                const pointsUpdated = points.concat({x : 0, y: 0});
                                setPoints(pointsUpdated);
                            }}className="bg-zinc-700 px-5 py-2 rounded transition hover:opacity-70 opacity-100 hover:-translate-y-1">+</button>

                            <button onClick={() => {
                                for(let i = 0; i < points.length; i++) {
                                    const x = parseInt((document.getElementById(`x-${i}`) as HTMLInputElement)!.value);
                                    const y = parseInt((document.getElementById(`y-${i}`) as HTMLInputElement)!.value);
                                    points[i]!.x = x;
                                    points[i]!.y = y;
                                }
                                // calculate using the shoelace formula
                                const vertices = points.concat(points[0]!);
                                let left = 0;
                                let right = 0;
                                for(let i = 0; i < points.length; i++) {
                                    left += vertices[i]!.x * vertices[i+1]!.y;
                                    right += vertices[i]!.y * vertices[i+1]!.x;
                                }
                                const area = Math.abs(left - right)*1.0 / 2.0;
                                setAnswer(area);
                            }}className="bg-zinc-700 px-5 py-2 rounded transition hover:opacity-70 opacity-100 hover:-translate-y-1">Calculate</button>
                        </div>
                        <p className="font-bold">Answer: <span className="font-light">{answer ?? 'Must enter vertices first!'}</span></p>
                    </div>
                </div>
            </main>
        </>
    );
}
